name: emin
channels:
  - conda-forge
  - conda-forge/label/libint_dev
  - defaults
dependencies:
  # Core dependencies
  - python==3.11
  - matplotlib
  - scikit-learn>=1
  - jupyterlab
  - pandas
  - pytest
  - flake8
  - pip

# Dependencies from the molecular design app
  - psi4==1.8=*py311*
  - pydantic<2
  - qcengine
  - xtb-python
  - psutil
  - tqdm

# Pip packages for all of them
  - pip:
      - -e . 
      - geometric>1
      - parsl>=1.*
